### ISSUE TITLE
[Packaging] Provide netstandard-compatible packaging of the SwaggerProvider

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#106]
### Description

There's a new packaging convention for type providers that enables a new assembly resolution algorithm in the compiler. This algorithm makes it possible for Type Providers to run on .Net core.

The format for packaging is `{packageRoot}/tools/typeproviders/{fsharpVersion}/{targetRuntime}/{targetArchitecture}`.
Now, any level of that deep path can be left off, as long as the resources at that level work for all possible child folder values.  Example: can just package assemblies at `{packageRoot}/tools/typeproviders/fsharp41` if dlls at that level work across all target runtimes and all target architectures.

As of right now, here are the value values for the placeholders:

- fsharpVersion: "fsharp41"
- targetRuntime: "net461", "net452", "net451", "net45", "netstandard2.0", "netcoreapp2.0"
- targetArchitecture: "x86", "x64"

NOTE: values taken from the code at https://github.com/Microsoft/visualfsharp/blob/master/src/fsharp/ExtensionTyping.fs#L46

So for a first pass, we should be able to package the current implementation, changing nothing else, under `{packageRoot}/tools/typeproviders/fsharp41/[net461,net452, net451, net45]`, right?

If you agree I can do this real quickly. I'd imagine that this would be in addition to the current packaging.  Then, we could look at creating a netcore build of this type provider and adding in the netstandard2.0 and netcoreapp2.0 targets.

**Comment by sergey-tihon** [comment]
We will definitely do it once, but my initial feeling that this should be done after #92 ...

Do you understand how new packaging will play with VS 2015? How to do packaging that works for both (old and new) compilers/ide?

**Comment by sergey-tihon** [comment]
I think that it is done in `dev` branch and relaesed in [v0.10.0-beta05](https://www.nuget.org/packages/SwaggerProvider/0.10.0-beta05)
