### ISSUE TITLE
.Net Standard cross-targeting

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#109]
### Description

We should ship SwaggerProvider as a cross-targeting TP in time for 1.0.  This will be non-trivial.  As I see it, the step we'd need to take are

1. Update TPSDK file dependencies and ensure that we still successfully build + test afterwards.
2. Convert to dotnet SDK still under net46. this will likely involve having to update other dependencies to versions that provide netstandard components, or migrating large amounts of code (I'm looking at you, ASP.Net WebAPI test controllers)
3. Ensure we build and run on net46 post conversion.
4. Add multitargeting to .netstandard2.0. This will likely result in even more dependency changes.
5. Build and test on .netstandard2.0
6. Package the DLL according to the pattern shown in the FSharp.Data nuspec here: https://github.com/baronfel/FSharp.Data/blob/c4c2b23baec79a7b4289b94d0c081a7844c59350/nuget/FSharp.Data.nuspec
7. Test the package with a .netstandard library/.netcoreapp2.0 consumer

Make sense?

**Comment by sergey-tihon** [comment]
I did some steps in migration directions during fsharp exchange, but I cannot compile TP projects - WIP version in #110 PR

**Comment by baronfel** [comment]
oh that's great! I'll clone it down and see if I can see the issue.

**Comment by sergey-tihon** [comment]
can we keep building for `net45` instead of `net46`?
