### ISSUE TITLE
tutorial is out of date

### ISSUE THREAD

**Issue by ChrisCanCompute** [fsprojects/SwaggerProvider#111]
### Description

The tutorial [here](http://fsprojects.github.io/SwaggerProvider/tutorial.html) is out of date.

### Repro steps

N/A

### Expected behavior

The page should display compilable code:

- static methods for types (e.g. `let tag = PetStore.Tag()`)
- instance methods for endpoints (e.g. `PetStore().GetPetById(6L)`)

### Actual behavior

Presumably old behaviour is displayed:

- types `let tag = PetStore.Definitions.Tag()`
- endpoints `PetStore.Pet.GetPetById(6L)`

### Known workarounds

N/A

### Related information 

N/A

**Comment by sergey-tihon** [comment]
@ChrisCanCompute What version did you use? latest release or pre-release?

**Comment by ChrisCanCompute** [comment]
Whatever nuget pulled in. I'll check when I get to work.

**Comment by ChrisCanCompute** [comment]
I was using v0.8.2

**Comment by sergey-tihon** [comment]
New one is published on landing page
http://fsprojects.github.io/SwaggerProvider/#/
