### ISSUE TITLE
Support Swagger 1.2 specification (or add parameter for openapi version)

### ISSUE THREAD

**Issue by jkone27** [fsprojects/SwaggerProvider#113]
### Description

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md (not does not work because fails to parse swagger version (in old spec is SwaggerVersion node, new is swagger )

### Repro steps

setup a swagger endpoint with an older version e.g. 1.2 swagger/openapi specs

### Expected behavior

It would be nice to add an additional parameter, e.g.
type MyApi = SwaggerProvider<"https://myApi/my-docs", version=1.2> or have it try parse automatically based on the json payload returned by openapi/swagger manifest

### Actual behavior

parsing fails and type provider cannot be used for older openapi versions

**Comment by sergey-tihon** [comment]
Sorry, but I think that `1.2` will not be supported ever.

In the future we plan to kill our own schema parser and migrate to OpenAPI.NET https://github.com/fsprojects/SwaggerProvider/issues/98 that support V2 and V3 schema formats.

`1.2` is too old to implement and support new parser for it.
 As workaround you may search for tool that can automatically convert from 1.2 to 2.0, like https://stackoverflow.com/questions/35913640/swagger-migration-from-1-2-to-2-0-specification/35994150#35994150
