### ISSUE TITLE
Failing to compile in common scenario calling array member

### ISSUE THREAD

**Issue by adamjones1** [fsprojects/SwaggerProvider#115]
Hi,

It looks like whenever a spec has an operation which returns a type containing an array of custom types, the type provider fails to compile at the point of calling that array member. Minimal repro at https://github.com/adamjones1/swagger-provider-error. (It compiles fine if line 9 of `Program.fs` calling `.Items` is commented out.) This is using version 0.8.2, though I only encountered the issue this week curiously - possibly the spec I was using changed in that time.

The reported error is: 
_"FS3033	The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error in the context of provided type 'SwaggerProvider.MyTypeProvider+Response', member 'get_Items'. The error: The operation 'Namespace' on item 'Item[]' should not be called on provided type, member or parameter"_

**Comment by michalkovy** [comment]
We started seeing the same issue and we haven't changed our source code either. Maybe new Visual Studio update came with some component that changed behavior?

**Comment by michalkovy** [comment]
Can you please create new NuGet beta package from current dev branch? It seems that new beta would work for us - older has problem for us not working with new Newtonsoft.Json library, thanks.

**Comment by sergey-tihon** [comment]
Could you please try [0.10.0-beta05](https://www.nuget.org/packages/SwaggerProvider/0.10.0-beta05) it is build from latest dev

**Comment by adamjones1** [comment]
That build isn't working for us (I get another compiler error message when calling the ctor of the provider) but is there any chance we could get a hotfix for the current issue on the release package? If there's anything I can do to help, let me know.

**Comment by sergey-tihon** [comment]
@adamjones1 could you please share more details about error that you see?

You sample (with minor changes) compiles in VS for Mac (2017 & 2019 Preview)

<img width="1110" alt="fullscreen_2_28_19__8_39_pm" src="https://user-images.githubusercontent.com/1197905/53586451-424eb400-3b99-11e9-8b99-9bae4bea6889.png">

**Comment by adamjones1** [comment]
Ah, apologies I wasn't aware the API had changed in the dev package - after updating the client as per your screenshot above the 0.10.0-beta05 one worked for me.

**Comment by adamjones1** [comment]
I'm not sure if this issue is already known but I'm getting a problem with Intellisense when using the 0.10.0-beta05 package:

![image](https://user-images.githubusercontent.com/47923806/54870136-4bd6d080-4d81-11e9-8cdb-3f949c971ca5.png)

paket.dependencies is just 
```
source https://api.nuget.org/v3/index.json

nuget FSharp.Core 
nuget SwaggerProvider 0.10.0-beta05 prerelease
```

I've verified it with the project targeting both `netcoreapp2.1` and `net462`. It appears to be dependent on the `open System` line earlier in the file.

**Comment by sergey-tihon** [comment]
Looks fine with latest released beta. Please reopen if you can reproduce
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/1197905/68328738-eb628c80-00e0-11ea-8a49-7f10e73a77c3.png">
