### ISSUE TITLE
Supporting DateTimeOffset

### ISSUE THREAD

**Issue by stevewillcock** [fsprojects/SwaggerProvider#119]
Hi,

Currently the type provider generates dates as System.DateTime. Ideally (for us!) this would be DateTimeOffset. [RFC3339](https://tools.ietf.org/html/rfc3339#section-5.6) includes a time zone and currently we'd be losing this time zone information across our Swagger API interface if we use the swagger provider as-is. Would you be open to accepting a pull request that added a configuration option to use System.DateTimeOffset rather than System.DateTime for date / date-time types?

I've seen [issue 14](https://github.com/fsprojects/SwaggerProvider/issues/14) which would also solve our issue but that looks like a bigger piece of work (as it likely involves two compilation pipelines and two nuget artefacts and the ability to support ad-hoc pluggable types). This approach would not restrict the option to support pluggable types / NodaTime in the future but it would provide some flexibility in the near-term.

Thanks

**Comment by stevewillcock** [comment]
Hi, we're using a different swagger provider now so to avoid overloading your issues list I'll close this one, thanks!

**Comment by sergey-tihon** [comment]
Let's keep it open. I think that `DateTimeOffset` should be used by default and probably be not configurable. Pluggable types like NodaTime is more complicated option which is less likely will be implemented.

@stevewillcock what swagger provider you decided to use? (just for the record)

**Comment by stevewillcock** [comment]
Great, I think it makes sense to go with DateTimeOffset. We went with NSwag for now (with build-time C# code generation) as we want to target OpenAPI 3. It would be great to use this again in the future though, the Type Provider approach seems to work nicely.

**Comment by sergey-tihon** [comment]
Changed inn #133 and will be part of next release (v0.10.0-beta11)
