### ISSUE TITLE
Port to Java with Manifold?

### ISSUE THREAD

**Issue by rsmckinney** [fsprojects/SwaggerProvider#124]
This is an interesting project, well done!

Java now has support for type providers via [project Manifold](https://github.com/manifold-systems/manifold).  Manifold calls them _type **manifolds**_, but the concept is the same.  The project already provides manifolds for [JSON Schema](http://manifold.systems/docs.html#json-and-json-schema), [YAML](http://manifold.systems/docs.html#yaml), [GraphQL](http://manifold.systems/docs.html#graphql), and others, but a Swagger manifold would be awesome and could potentially leverage stock manifolds for JSON and YAML.

So I wonder if there is interest here in porting the SwaggerProvider to Java using Manifold?

**Comment by sergey-tihon** [comment]
I do not mind if parts of this project will be used Manifold/Java implementation of Swagger/OpenAPI  manifold. But I am not going to do it myself, sorry.
