### ISSUE TITLE
Intellisense not working in 0.10.0 beta packages

### ISSUE THREAD

**Issue by adamjones1** [fsprojects/SwaggerProvider#130]
I'm not sure if this issue is already known but I'm getting a problem with Intellisense when using the 0.10.0-beta05 package:

![image](https://user-images.githubusercontent.com/47923806/54870136-4bd6d080-4d81-11e9-8cdb-3f949c971ca5.png)

paket.dependencies is just 
```
source https://api.nuget.org/v3/index.json

nuget FSharp.Core 
nuget SwaggerProvider 0.10.0-beta05 prerelease
```

I've verified it with the project targeting both `netcoreapp2.1` and `net462`. It appears to be dependent on the imported namespaces in the file, `open System` is sufficient to trigger it. I think it appears on a per-file basis so affected files will have no Intellisense on any symbol at all. (Also verified this doesn't occur with the 0.8.2 package.)

_Originally posted by @adamjones1 in https://github.com/fsprojects/SwaggerProvider/issues/115#issuecomment-475894223_

**Comment by adamjones1** [comment]
^ Reopening as a separate issue as it's not the same as what #115 was raised for.

I can still reproduce this using 0.10.0-beta10 (in both VS and Ionide).

**Comment by sergey-tihon** [comment]
@adamjones1 can you please push all  your code to https://github.com/adamjones1/swagger-provider-error ?

**Comment by sergey-tihon** [comment]
Can you also try `netcoreapp3.0`?
I have no idea yet, how it can affect intellisense when you do not use TP.

**Comment by adamjones1** [comment]
Sure - so it got a little more interesting, I pushed a minimal counterexample to that repo (master branch) and found that the issue was no longer present. However if I switched it to use Paket rather than NuGet, which I had been using in my previous test, the issue resurfaced. I pushed that in branch `with-paket`, you should be able to repro it there. All on .net core 3.0.

Not sure why it would be unhappy with Paket though I notice when using it I get a whole lot more referenced packages in the project from transitive dependencies than I do with NuGet:
![image](https://user-images.githubusercontent.com/47923806/68337715-7af34580-00b7-11ea-858b-cf1be93c110a.png)
So possibly it's some clash with one of these.

**Comment by sergey-tihon** [comment]
Can you please try on your machine explicitly specify target framework in `paket.dependencies` file
and run `paket install`

```
source http://nuget.orbis.com/api/v1
source https://api.nuget.org/v3/index.json
frameworks: netcoreapp3.0

nuget FSharp.Core
nuget SwaggerProvider 0.10.0-beta10 prerelease
```

**Comment by adamjones1** [comment]
Now it appears to work :)

**Comment by sergey-tihon** [comment]
@adamjones1 can we consider this as resolved?

**Comment by adamjones1** [comment]
Yeah, I think the issue should be documented but this thread probably serves that purpose good enough since it's quite minor.
