### ISSUE TITLE
FSI Errors

### ISSUE THREAD

**Issue by tick-rick** [fsprojects/SwaggerProvider#135]
### Description

It seems that SwaggerProvider does not work via latest dotnet fsi. I don't have a whole repro, but the code is very simple. It seems to create the actual swagger types properly `type Api = OpenApiClientProvider<Schema>` works fine, the error comes from `let client = Api.Client()`

```
error FS3216: constructor '.ctor' not found in type 'SwaggerProvider.Api' from assembly 'tmpCsOltC, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. A possible cause may be a version incompatibility. You may need to explicitly reference the correct version of this assembly to allow all referenced components to use the correct version.
```

Further, when trying to work around the issue by doing this:
```let test (client:Api.Client) = client.GetStatus("abc","123")``` , the following error occurs in FSI:
```
error FS0192: internal error: convMethodRef: could not bind to method '""' of type 'SwaggerProvider.Api, tmpCsOltC, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
```

### Related information 
- linux:
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

**Comment by sergey-tihon** [comment]
Can you share repro? I am interested how you restores dependencies NuGet/Paket and how you load dlls in FSI (`#r` names & `#I` paths used)

**Comment by tick-rick** [comment]
Sorry for lateness, the server to create repro is huge. references.fsx is just made using vscode 'generate fsi references'. there is nothing sophisticated about it, the provider is loaded like this:

```
#I "/home/user/.nuget/packages"
#r "swaggerprovider/0.10.0-beta11/lib/netstandard2.0/SwaggerProvider.Runtime.dll"
```

**Comment by sergey-tihon** [comment]
The right solution is direct package reference directly using FSI, but this feature is not yet available in standalone version of FSI - https://github.com/fsharp/fslang-suggestions/issues/542

For now, closest alternative is [paket generate-load-scripts](https://fsprojects.github.io/Paket/paket-generate-load-scripts.html#paket-generate-load-scripts)

**paket.dependencies**
```
source https://api.nuget.org/v3/index.json

storage: none
framework: netcore3.0, netstandard2.0, netstandard2.1

nuget SwaggerProvider prerelease
```

1. create `paket.dependencies` using sample above
2. install dependencies `dotnet paket install` (you need SwaggerProvider v0.10.0-beta13)
3. generate load script `dotnet paket generate-load-scripts`
4. execute your script using FSI shipped with .NET Core `dotnet fsi repl.fsx`

**repl.fsx**
```fsharp
#load ".paket/load/netstandard2.0/SwaggerProvider.fsx"

open SwaggerProvider

let [<Literal>]schema = "http://petstore.swagger.io/v2/swagger.json"
type PetStore = SwaggerClientProvider<schema>
let petStore = PetStore.Client()
```

This is the easiest way to load all required assemblies.

**Comment by tick-rick** [comment]
I think this is a fair work around, annoying that it is internal errors, rather than dependency error, but i suspect this is a limitation of current FSI.
