### ISSUE TITLE
Fail to get autocompletion 

### ISSUE THREAD

**Issue by evilz** [fsprojects/SwaggerProvider#142]
### Description

All IDE fails to get autocomplet from client.

### Repro steps

Basic usage :

```ocaml
[<Literal>]
let Schema = __SOURCE_DIRECTORY__ + "/Contract/campaign-swagger.json"
type Campaign = OpenApiClientProvider<Schema>

let client = Campaign.Client()
client.****
```

![image](https://user-images.githubusercontent.com/2937862/76207130-838e9080-61fd-11ea-8416-d026b45dc304.png)

### Expected behavior

List all methods generated

### Actual behavior

display a 'Note'node 

### Known workarounds

none, sometime it works ^^, Compilation always ok.

### Related information 

* Operating system : Windows 10
* `<PackageReference Include="SwaggerProvider" Version="0.10.0" />`
* netcoreapp3.1

Try in VS2019, VS code and Rider

**Comment by jkone27** [comment]
I have the same, <Note> appears. tried in VS2019. this is kind of bad for such a great type provider ... the old "SwaggerProvider" type provider (deprecated one) still works though

**Comment by sergey-tihon** [comment]
Can you please try [SwaggerProvider v0.10.2](https://www.nuget.org/packages/SwaggerProvider/0.10.2)
It should provide better autocomplete experience in IDEs

**Comment by evilz** [comment]
Looks good! ❤
