### ISSUE TITLE
dotnet core (windows) + fsautocomplete woes

### ISSUE THREAD

**Issue by fradav** [fsprojects/SwaggerProvider#147]
### Description

FsAutocomplete (in vscode-ionide) fails to load the package with dotnet core

### Repro steps

Exactly as stated [in the "Getting Started" section](http://fsprojects.github.io/SwaggerProvider/#/#getting-started),
except for the version, 0.10.2 (tried 0.10.0 too)

### Expected behavior

Should open without error in fsac.

### Actual behavior

```plain
The type provider 'C:\Users\Franc\.nuget\packages\swaggerprovider\0.10.0\lib\netstandard2.0\SwaggerProvider.Runtime.dll' reported an error: Assembly attribute 'TypeProviderAssemblyAttribute' refers to a designer assembly 'SwaggerProvider.DesignTime.dll' which cannot be loaded or doesn't exist. Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Le fichier spécifié est introuvable.F# Compiler(3031)
Referenced assembly 'C:\Users\Franc\.nuget\packages\swaggerprovider\0.10.0\lib\netstandard2.0\SwaggerProvider.Runtime.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were foundF# Co
```

![image](https://user-images.githubusercontent.com/701587/80455162-8e2af380-892b-11ea-9e17-932f1aea954a.png)

### Known workarounds

Reverting fsac to .net runtim works.

### Related information 

* Operating system : windows 10
* .NET Runtime, CoreCLR or Mono Version : dotnet sdk 3.1.201
vscode + ionide 4.9

**Comment by sergey-tihon** [comment]
I believe that this is rated to recent FCS release https://github.com/fsharp/FsAutoComplete/issues/565
not a particular type prover issues.

**Comment by fradav** [comment]
No problem with VS 2019, but I doubt it is using netcore runtime for its intellisense background process. I could be wrong.

**Comment by fradav** [comment]
Ok probably a fsac issue, then. That's weird because it is working fine with FSharp.Data's TPs in netcore. Closing issue.
