### ISSUE TITLE
Generating JSON Schema Object?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SwaggerProvider#151]
I know this is a bit off-topic, but many times I found that Swagger OpenAPI 3.0 API providers don't publish their schema JSON file for whatever reason. Instead they have some kind of generated developer web-site documentation of examples.

Can I generate the schema file somehow?
Or could I work with SwaggerProvider with just a bunch of API-endpoints and response-request JSON examples?
Or should I just fall-back to FSharp.Data JsonProvider?

I'm ok with the JsonProvider, but it's a bit painful if the API has lot of resource endpoints.

**Comment by sergey-tihon** [comment]
Can you share the sample of such provider?

As far as I know, all (most of) tools like swagger-ui and ReDoc UI are built on top of schema.
So server generate schema and then tool generate `developer web-site documentation of examples` from schema.

so I believe that schema also should be available


__Swagger UI__
http://petstore.swagger.io:8080
http://petstore.swagger.io:8080/api/v3/openapi.json

__ReDoc UI__
https://redocly.github.io/redoc/
https://petstore.swagger.io/v2/swagger.json

maybe you can guess URI adding `openapi.json` / `swagger.json` ?

**Comment by Thorium** [comment]
I haven't guessed the name, and also the people we usually work with when starting the integrations are rather pre-sales people than customer services, so to get in touch with the actual developers is not always fast and trivial.

Currently I'm looking for using [OpenWrks](https://www.openwrks.com/) API (open banking aggregator):
https://developers.openwrks.com/#introduction


Other Swagger APIs that I've tried:

[ShieldPay](https://www.shieldpay.com/) (payments) but that wasn't Swagger 2.0 at least back then:
http://apiuat.shieldpay.com/swagger/

..and [ClearBank](https://www.clear.bank/) (banking), they seem to have schema available:
https://institution-api-sim.clearbank.co.uk/docs/index.html?urls.primaryName=V3

Also there are other APIs looking like Swagger APIs but not actively advertising it,
like [OnFido](https://onfido.com/) (identity check):
https://documentation.onfido.com/#getting-started-with-api-v3

**Comment by sergey-tihon** [comment]
ShieldPay - https://apiuat.shieldpay.com:443/swagger/docs/v5
ClearBank - https://institution-api-sim.clearbank.co.uk/docs/v3/api.json
OnFido - it is powered by [Slate](https://github.com/slatedocs/slate). not sure how its work really, it may not use swagger/open api
OpenWrks - it is not clear for me as well

**Comment by Thorium** [comment]
Onfido seems to have OpenAPI yaml specs at https://github.com/onfido/onfido-openapi-spec so maybe that can be used somehow by SwaggerProvider.

For the OpenWrks, I got response "We don’t have a schema file I’m afraid", so maybe that is some custom implementation... Maybe a schema could be created somehow via inspector.swagger.io and swaggerhub, but probably it's easier to just go with the FSharp.Data JsonProvider.

**Comment by sergey-tihon** [comment]
Yes, Yaml is currently supported, so just use it instead of json

Also you may check specs here https://apis.guru/browse-apis/
but I am afraid that there is nothing to OpenWrks

**Comment by Thorium** [comment]
One more payment API, do you happen to know if [Modulr](https://www.modulrfinance.com/) is Swagger/OpenApi or not:
https://modulr.readme.io/reference

**Comment by Thorium** [comment]
> Yes, Yaml is currently supported, so just use it instead of json

There is not a single but many different YAML-files, can I somehow import them all or should I merge them somehow?

**Comment by sergey-tihon** [comment]
Sorry no idea about Modulr.
Also do not  know about tools to merge Yaml files...
It should be possible to implement (external schemas auto discovery) but it is not yet supported.
