### ISSUE TITLE
Case sensitivity on .ToString() ?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SwaggerProvider#172]
I'm using API that needs a SHA256 hash over the request body, added in the headers.

When I do `mySwaggerRequestBodyObject.ToString()` I get: `{"MySum": 123}`
but when I include this item to an actual request that is posted via SwaggerProvider POST, looking with Fiddler, the body has `{"mySum": 123}`

...which is obviously a problem as the SHA calculated over my mySwaggerRequestBodyObject doesn't match the body calculated by the other side.

**Comment by Thorium** [comment]
Found it, I have to use the custom Serialize method

```fsharp
        let client = MySwagger.Client(new System.Net.Http.HttpClient())
        let toHash = client.Serialize(req)
```

**Comment by Thorium** [comment]
I'm still not able to match the hash on server side (annoyingly hidden to me).
Maybe there are some spaces or something... Is there a built-in way to get exact payload of the request body sent to the server?

**Comment by sergey-tihon** [comment]
You may try to implement custom DelegatingHandler - http://fsprojects.github.io/SwaggerProvider/#/Customization#request-interception
