### ISSUE TITLE
Support for Dictionaries

### ISSUE THREAD

**Issue by toburger** [fsprojects/SwaggerProvider#173]
### Description

It looks like dictionaries aren't supported and simply return an `obj`.

### Repro steps

Run the following code as script;

```fsharp
#r "System.Net.Http"
#r "nuget: SharpYaml"
#r "nuget: SwaggerProvider"

open SwaggerProvider

type TourismOpenDataHub =
    OpenApiClientProvider<
        "https://api.tourism.testingmachine.eu/swagger/v1/swagger.json",
        PreferAsync = true,
        IgnoreControllerPrefix = true
    >

let client = TourismOpenDataHub.Client()

let poiResult =
    client.GetApiPoi()
    |> Async.RunSynchronously

poiResult.Items
|> Seq.map (fun item -> item.Id, item.Detail)
```

### Expected behavior

The Detail property should be a `Dictionary<string, Detail>` or `Map<string, Detail>`:

![image](https://user-images.githubusercontent.com/728782/102361855-fbbb8b00-3fb3-11eb-9ffb-b7b61e8a6afa.png)

So I expect this to work:

```fsharp
poiResult.Items
|> Seq.map (fun item -> item.Id, item.Detail.["en"].Title)
```

### Actual behavior

![image](https://user-images.githubusercontent.com/728782/102361911-0b3ad400-3fb4-11eb-87c3-d867e6ec5053.png)

### Known workarounds

Untyped access is possible so at least it can be worked around the problem.

**Comment by sergey-tihon** [comment]
Seems that you are right 😊
According to the spec https://swagger.io/docs/specification/data-models/dictionaries/ `Details` definitions is Dictionary
```json
          "Detail": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/components/schemas/Detail"
            },
            "nullable": true
          },
```

Above[ this line](https://github.com/fsprojects/SwaggerProvider/blob/master/src/SwaggerProvider.DesignTime/v3/DefinitionCompiler.fs#L299) we need to do a check for `object` with `additionalProperties`, then infer element type ([like we do for array items](https://github.com/fsprojects/SwaggerProvider/blob/master/src/SwaggerProvider.DesignTime/v3/DefinitionCompiler.fs#L322)) and return [Map with correct item type](https://github.com/fsprojects/SwaggerProvider/blob/master/src/SwaggerProvider.DesignTime/v2/DefinitionCompiler.fs#L285-L286)

Do you want to do PR with the fix?

**Comment by toburger** [comment]
Thanks for the hints on how to get this resolved Sergey!
I will try to fix it!
Should I use a `Map` or a `Dictionary` for the type?

**Comment by sergey-tihon** [comment]
I suggest to try Map (as we do in V2/SwaggerProvider) it should work fine with Json.NET Serializer 

>Any advice on how to test the provider?

Add tests in the PR
1. Add one more controller that [return Dictionary](https://github.com/fsprojects/SwaggerProvider/blob/master/tests/Swashbuckle.WebApi.Server/Controllers/ReturnControllers.fs)
2. Add [test that call new endpoint](https://github.com/fsprojects/SwaggerProvider/blob/master/tests/SwaggerProvider.ProviderTests/v3/Swashbuckle.ReturnControllers.Tests.fs)
3. Ideally add tests that send and it back [here](https://github.com/fsprojects/SwaggerProvider/blob/master/tests/SwaggerProvider.ProviderTests/v3/Swashbuckle.ReturnControllers.Tests.fs) and [here](https://github.com/fsprojects/SwaggerProvider/blob/master/tests/Swashbuckle.WebApi.Server/Controllers/UpdateControllers.fs)

**Comment by toburger** [comment]
PR: #174
