### ISSUE TITLE
FS3033: Payload is not supported

### ISSUE THREAD

**Issue by jkone27** [fsprojects/SwaggerProvider#181]
### Description

```fsharp
[<Literal>]
let openApi= __SOURCE_DIRECTORY__ + "/SWopenapi.yaml"

//OpenApi type provider
type MyApi = OpenApiClientProvider<openApi>
```

### Repro steps

the Openapi spec is valid :
https://apitools.dev/swagger-parser/online/

but the type provider give an unknown error (also hard to fix , try to patch in the openapi yaml eventually)

[SWopenapi.txt](https://github.com/fsprojects/SwaggerProvider/files/6171012/SWopenapi.txt) 

>> attached yaml file (change extension)

### Expected behavior

The type provider works

### Actual behavior

```cli
error FS3033: The type provider 'SwaggerProvider.OpenApiClientTypeProvider' reported an error: Payload 'quantityIdentityId' is not supported
```

Please provide a description of the actual behavior you observe. 

### Known workarounds

None i could find, not clear what's wrong in the openapi definition as that's valid according to online parsers

### Related information 

* Windows 10
* latest nuget package
* NET5
* Both vs2019 and vscode give errors

**Comment by sergey-tihon** [comment]
Fixed in latest package
```fsharp
#r "nuget: SwaggerProvider, 1.0.0-beta3"
open SwaggerProvider

let [<Literal>] openApi= __SOURCE_DIRECTORY__ + "/schema.yaml"
type MyApi = OpenApiClientProvider<openApi>
```

<img width="1131" alt="test_fsx_—_SwaggerProvider" src="https://user-images.githubusercontent.com/1197905/111868239-1a496d80-8979-11eb-8ffd-6e8427a9ffd0.png">

**Comment by jkone27** [comment]
awesome! :) will try this out when the new package is released, thank you so much @sergey-tihon 🥇
