### ISSUE TITLE
Ignored schema components while generating the types

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fsprojects/SwaggerProvider#183]
### Description

While working on [Hawaii](https://github.com/Zaid-Ajaj/Hawaii), I am using a modified PetStore schema and testing with the type provider to see how the results look like and whether I am on the right direction. 

For the following [schema](https://gist.github.com/Zaid-Ajaj/f1f82ad9cb4bc324652205fa0b715e3e), the `Pet` type is completely ignored:

![2021-05-15 01_48_48-ConsoleApp17 - Microsoft Visual Studio](https://user-images.githubusercontent.com/13316248/118341547-d9587a00-b51f-11eb-80c0-2fe8ff324a90.png)

Besides `Pet`, the global `UserRole` enum seems to also be ignore :
```json
{
  "UserRole": {
      "type": "string",
      "enum": [ "admin", "user" ]
    }
}
```
and references to that `UserRole` type in other components (such as `User.Role`) is resolved to a string instead of an enum

![2021-05-15 01_53_31-ConsoleApp17 - Microsoft Visual Studio](https://user-images.githubusercontent.com/13316248/118341769-a8c51000-b520-11eb-9e1b-e896ef7cad2a.png)

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a new console app and add `SwaggerProvider v0.12.0` package (1.0.0-beta3 didn't work for me, causing a design time error)
2. Create the generated types from the schema provided with the link abode
3. Observe the missing `Pet` type and `UserRole` type

### Expected behavior

Types are not ignored 

### Actual behavior

Types are ignored

### Known workarounds

None

### Related information 

* Operating system: Windows 10
* Branch: master
* .NET Runtime: core sdk 5.0.200
* Performance information, links to performance testing scripts: n/a

**Comment by Zaid-Ajaj** [comment]
About my comment:
> 1.0.0-beta003 didn't work for me, this should another issue, really. This happened:

![2021-05-15 01_53_31-ConsoleApp17 - Microsoft Visual Studio](https://user-images.githubusercontent.com/13316248/118342096-36edc600-b522-11eb-87e9-82ed9eff2f2b.png)

Using dotnet 5.0.200 and a console project with default settings
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="petstore.json" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SwaggerProvider" Version="1.0.0-beta3" />
  </ItemGroup>

</Project>
```

Building the project worked but I get the design-time error above when hovering over the reported error in visual studio

**Comment by sergey-tihon** [comment]
> the Pet type is completely ignored:

in your `modified PetStore schema` Pet defined as Dictionaty instead of object, that's why object is not generated.
```json
        "Pet": {
            "type": "object",
            "additionalProperties": {
                "type": "integer",
                "format": "int64"
            },
```
compare it with spec for dictionaries https://swagger.io/docs/specification/data-models/dictionaries/
after merging https://github.com/fsprojects/SwaggerProvider/pull/174 such object compiled as `Map<_,_>`

> global UserRole enum seems to also be ignore 

Swagget/OpenAPI TPs model enums as string, that is why there is no type - https://github.com/fsprojects/SwaggerProvider/issues/146

> 1.0.0-beta003 didn't work for me, this should another issue, really. This happened:

What IDE & version do you use?
Looks OK in Microsoft Visual Studio Enterprise 2019 Version 16.9.5
<img width="776" alt="image" src="https://user-images.githubusercontent.com/1197905/118391665-ca63eb80-b635-11eb-8f70-2cbce8d95b79.png">

**Comment by Zaid-Ajaj** [comment]
Hi @sergey-tihon I must have misunderstood the specifications of additional properties because object types using additionalProperties are also allowed to have arbitrary object properties alongside additionalProperties 🤔 at least the schema parsers and validators are perfectly fine when reading the schema and don't report any error. 

Maybe I could simplify my implementation 😅 

As for the VS type provider error, I will try to see what's going on there, maybe a caching issue because I installed 1.0.0beta3 after 0.12.0 and Vs didn't dispose of loaded assemblies

**Comment by Zaid-Ajaj** [comment]
This is what I mean by object properties + additional properties
```json
"Lang": {
    "type": "object",
    "required": [
        "defaultLang"
    ],
    "properties": {
        "defaultLang": {
            "type": "string"
        }
    },
    "additionalProperties": {
        "type": "string"
    }
}
```
The type `Lang` is a dictionary of `string -> string` but will always have a `defaultLang` property. Generating `Map<string, string>` is probably good enough but for Hawaii I am having it generate a specialized type
```fs
type Lang =
    { defaultLang: string
      additionalProperties: Map<string, string> }
```
It makes the JSON conversion somewhat more complicated but I already took care of that. 

As for the issue, it is resolved since the my schema was a bit too contrived to begin with and the type provider doesn't generate specialized enums
