### ISSUE TITLE
1.0.0-beta5 in .net5 project - Could not load file or assembly System.Buffers

### ISSUE THREAD

**Issue by rchybicki** [fsprojects/SwaggerProvider#188]
Description:
Version 1.0.0-beta5
project .net5 library
paket 

referencing SwaggerProvider causes:
error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)

I've been using SwaggerProvider in this .net5 project for a while now, from a fork that I updated to support .net5. I recently did a rebase and since upstream merged the 'system_text_json' branch I cannot get 1.0.0-beta5 nor my fork to work.

I tried to research everything about referencing in the Reflection-only loader context but got nowhere. Tried adding System.Buffers to my project, changing System.Text.Json that depends on System.Buffers in my fork to prerelease - no go. I'd really appreciate a nudge in the right direction, not sure how to move forward.

**Comment by sergey-tihon** [comment]
@rchybicki do you repro for this that you can share?

**Comment by rchybicki** [comment]
Yes, just created one:
https://github.com/rchybicki/SwaggerProviderIssueRepro
This turned out to be a bit tricky, but it allowed to me narrow down what's causing the issue (without understanding why though).
The project starts failing with this error if it or any project it depends on uses FSharp.Data.SqlClient.

**Comment by sergey-tihon** [comment]
It is strange on macOS ...

`dotnet build` fail with error inside `fsc` msbuild task

>  /usr/local/share/dotnet/sdk/5.0.301/FSharp/Microsoft.FSharp.Targets(281,9): error MSB6006: "dotnet" exited with code 1. [/Users/sergey_tihon/git/sandbox/SwaggerProviderIssueRepro/src/SwaggerProviderIssueRepro/SwaggerProviderIssueRepro.fsproj]

but it build without error in `VS4Mac`
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/1197905/123326508-9e436080-d539-11eb-8a19-c916aefdcd45.png">
