### ISSUE TITLE
Where did the converters go on 1.0?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SwaggerProvider#194]
In the docs there is a sample of

```fsharp
            Swagger.Serialization.OptionConverter () :> JsonConverter
            Swagger.Serialization.ByteArrayConverter () :> JsonConverter
```

...but I cannot find these after updating to SwaggerProvider 1.0

**Comment by Thorium** [comment]
Here you go. just include these to your project and your old code compiles:

```fsharp
module Serialization =
    type OptionConverter() =
        inherit JsonConverter()

        override __.CanConvert(t) =
            t.IsGenericType && t.GetGenericTypeDefinition() = typedefof<option<_>>

        override __.WriteJson(writer, value, serializer) =
            let value =
                if isNull value then null
                else
                    let _,fields = Microsoft.FSharp.Reflection.FSharpValue.GetUnionFields(value, value.GetType())
                    fields.[0]
            serializer.Serialize(writer, value)

        override __.ReadJson(reader, t, _, serializer) =
            let innerType = t.GetGenericArguments().[0]
            let innerType =
                if innerType.IsValueType then (typedefof<Nullable<_>>).MakeGenericType([|innerType|])
                else innerType
            let value = serializer.Deserialize(reader, innerType)
            let cases = Microsoft.FSharp.Reflection.FSharpType.GetUnionCases(t)
            if isNull value then Microsoft.FSharp.Reflection.FSharpValue.MakeUnion(cases.[0], [||])
            else Microsoft.FSharp.Reflection.FSharpValue.MakeUnion(cases.[1], [|value|])

    type ByteArrayConverter() =
        inherit JsonConverter()
        override __.CanConvert(t) = t = typeof<byte[]>
        override __.WriteJson(writer, value, serializer) =
            let bytes = value :?> byte[]
            let str = System.Convert.ToBase64String(bytes)
            serializer.Serialize(writer, str)
        override __.ReadJson(reader, _, _, serializer) =
            let value = serializer.Deserialize(reader, typeof<string>) :?> string
            Convert.FromBase64String(value) :> obj
```

**Comment by sergey-tihon** [comment]
@Thorium do you think that converters should be part of the SwaggerProvider package?

What is wrong with out-of-the-box support of Options from [FSharp.SystemTextJson](https://github.com/Tarmil/FSharp.SystemTextJson)?

**Comment by Thorium** [comment]
As user I don't care the serialization as long as it works. This was more of migration issue, if you are using SwaggerProvider already and update, then your old code doesn't compile and the docs were also reflecting this old version with these code-lines.

**Comment by xperiandri** [comment]
@Thorium would you mind sending a PR with docs fix according to your findings?

**Comment by Thorium** [comment]
I actually went for using SwaggerProvider version 0.12.2 and I'm quite happy for that, works for me. Let others fight with Microsoft Json, and maybe in a few months I'll look again the migration.

**Comment by Thorium** [comment]
Ok, a few months (or a year) passed an I now tried SwaggerProvider 2.0 alpha and it worked well.

**Comment by Thorium** [comment]
I think there is still no snake_case support in System.Text.Json, so if you want to do snake_case, you still have to use Newtonsoft.

**Comment by Thorium** [comment]
...which is now released. So we could consider updates?

**Comment by sergey-tihon** [comment]
It is already released?

**Comment by Thorium** [comment]
yes, they released it yesterday with [dotnetconf](https://www.dotnetconf.net/)

**Comment by Thorium** [comment]
Specifically I'm interested how to do this on SwaggerProvider v2:
https://fsprojects.github.io/SwaggerProvider/#/Customization#serialization

The docs still use Newtonsoft so can it still be used with SwaggerProvider v2 or should I write something else.

**Comment by sergey-tihon** [comment]
We don't have an upper constrain for `System.Text.Json` version, so I would assume that the latest version should be used if it is referenced.

Can we create a test for your use case inside this project? Do you understand how can we emulate it?

**Comment by Thorium** [comment]
Seems to work with latest System.Text.Json.

Send PR to update the docs.
