### ISSUE TITLE
Using SwaggerProvider in a Fable application

### ISSUE THREAD

**Issue by francotiveron** [fsprojects/SwaggerProvider#199]
### Description

Using SwaggerProvider in a Fable application fails

### Repro steps

From the minimal Fable application, add SwaggerProvider and change the code as per from https://fsprojects.github.io/SwaggerProvider/#/#new-project
```
open Browser.Dom
open SwaggerProvider

let [<Literal>] Schema = "https://petstore.swagger.io/v2/swagger.json"
type PetStore = OpenApiClientProvider<Schema>

// Get a reference to our button and cast the Element to an HTMLButtonElement
let myButton = document.querySelector(".my-button") :?> Browser.Types.HTMLButtonElement

// Register our listener
myButton.onclick <- fun _ ->
    let client = PetStore.Client()

    let s = 
        client.GetInventory()
        |> Async.AwaitTask
        |> Async.RunSynchronously
        |> sprintf "%O"

    myButton.innerText <- s
```

### Expected behavior

The application works normally

### Actual behavior

While VS Code intellisense works properly, when I start the project I get the following exceptions

> C:/Root/Work/Horth/Work/Yatp/Client/Fable/src/App.fs(7,17): (7,46) error FSHARP: The type provider 'SwaggerProvider.OpenApiClientTypeProvider' reported an error: Could not load file or assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621) (code 3033)
> C:/Root/Work/Horth/Work/Yatp/Client/Fable/src/App.fs(17,27): (17,33) error FSHARP: The type 'PetStore' does not define the field, constructor or member 'Client'. (code 39)

### Known workarounds

None

### Affected Type Providers

- [ x] SwaggerClientProvider
- [x ] OpenApiClientProvider

### Related information

* Windows 10
* .NET 6

**Comment by sergey-tihon** [comment]
@francotiveron SwaggerProvider does not support Fable, we do not emit code compatible with browsers.

I recommend to try another project - https://github.com/Zaid-Ajaj/Hawaii
Hawaii pretty flexible and configurable CLI tool that can generate F# clients based on Swagger/OpenApi schema compatible with Fable.

**Comment by francotiveron** [comment]
Thanks
