### ISSUE TITLE
Provider crashes having number at the end of created type name

### ISSUE THREAD

**Issue by xperiandri** [fsprojects/SwaggerProvider#204]
### Description

I tried to declare `type SambaSafetyQortaV1 = SwaggerProvider.OpenApiClientProvider<"v1.yaml">`
And it fails with
`FS3057	The type provider 'SwaggerProvider.OpenApiClientTypeProvider' returned an invalid type from 'ApplyStaticArguments'. A type with name 'SambaSafetyQortaV1' was expected, but a type with name 'SambaSafetyQortaV' was returned.`

### Repro steps

Declare type from type provider with a number at the end

### Expected behavior

Type compiles

### Actual behavior

Error

### Affected Type Providers

- OpenApiClientProvider

### Related information

2.0.0-beta4

**Comment by sergey-tihon** [comment]
@xperiandri can you share `v1.yaml` or smaller schema with the same error?

**Comment by xperiandri** [comment]
[v1.zip](https://github.com/fsprojects/SwaggerProvider/files/9484506/v1.zip)

**Comment by xperiandri** [comment]
https://app.swaggerhub.com/apis-docs/SambaSafety/Customer_API/v1#/

**Comment by xperiandri** [comment]
By the way it generates nothing from that file

**Comment by sergey-tihon** [comment]
Your schema contains external references, instead of real definitions.
```
paths:
  /oauth2/v1/token:
    $ref: 'https://api.swaggerhub.com/domains/SambaSafety/Authorization/1.0#/components/token'
  /oauth2/v1/revoke:
    $ref: 'https://api.swaggerhub.com/domains/SambaSafety/Authorization/1.0#/components/revokeToken'
```

Current TP does not support resolving and loading schema parts.

**Comment by xperiandri** [comment]
But why without `1` at the end it is just empty but not display any errors?

**Comment by sergey-tihon** [comment]
Next version(beta) will report proper error that such schemas are not supported
