### ISSUE TITLE
Introduce Async/Task-based calls for the Operations

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#21]
### Description

The current version of the SwaggerProvider only exposes synchronous network calls.  It would be excellent if we had Async or Task-based versions as well, for throughput reasons.
I don't know which representation (Async or Task) would be best, especially because the operations from this library are often consumed by C# code.
### Expected behavior

Asyncronous versions of the operations would be made available.
### Actual behavior

Only synchronous versions of operations are present.
### Known workarounds

You can manually manage Tasks/Asyncs of synchronous operations via the old-style BackgroundWorker/IAsyncResult mechanisms if you so wish.

**Comment by 7sharp9** [comment]
I would say asynchronous calls is a must, I would not expect any calls to be synchronous.  In terms of Task/Async I would say support both, use a param on the TP to generate the non default one.

**Comment by sergey-tihon** [comment]
Released in [v0.10.0-alpha9](https://www.nuget.org/packages/SwaggerProvider/0.10.0-alpha9) thanks to @baronfel !
