### ISSUE TITLE
Cannot generate OpenApiClientProvider for Mews endpoint

### ISSUE THREAD

**Issue by petrkoutnycz** [fsprojects/SwaggerProvider#210]
### Description

Trying to generate client provider for Open Api in Mews company and it fails with weird exception. Other generators fail because of missing support of `oneOf` so it might be also the reason here thought the error is a bit cryptic.

### Repro steps

Please provide the steps required to reproduce the problem

1. Type provider type definition with parameters: just `OpenApiClientProvider<"https://api.mews.com/Swagger/connector/swagger.yaml">`

2. Sample schema or relevant schema part: https://api.mews.com/Swagger/connector/swagger.yaml

### Expected behavior

`OpenApiClientProvider` gets generated properly.

### Actual behavior

Compilation fails with `TypeProvidersConnection connection was lost`
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/9723402/204496250-81705e6c-63bf-4224-a019-b5b9acfb686b.png">

### Known workarounds

Don't know about any.

### Affected Type Providers

- [ ] SwaggerClientProvider
- [x] OpenApiClientProvider

### Related information

* Operating system: MacOS
* .NET Runtime, CoreCLR or Mono Version: .NET SDK 6.0

**Comment by sergey-tihon** [comment]
@petrkoutnycz it is strange, If you unable to run any TP then I would suggest to report the issue to Rider team.
