### ISSUE TITLE
Question about System.Net.Http dependency?

### ISSUE THREAD

**Issue by Thorium** [fsprojects/SwaggerProvider#217]
It seems that SwaggerProvider package have had a dependency to [System.Net.Http](https://www.nuget.org/packages/System.Net.Http) which itself has a dependency to 
[System.Runtime.WindowsRuntime](https://www.nuget.org/packages/System.Runtime.WindowsRuntime/).
where loading that causes F# intellisense crash in compiler, e.g. https://github.com/dotnet/fsharp/issues/14505

Could loading this dependency be avoided?

### Related information

* Operating system Windows 11
* .NET Runtime, CoreCLR or Mono Version: .NET 7.0.101 and .NET Framework 4.7.2

**Comment by sergey-tihon** [comment]
I believe `HttpClient` come from this package, so we definitely need it in runtime. I believe we also need it in the design type, because TP emits constructors that accept `HttpClient` as an argument.

@Thorium have you tried to target `netstandard2.1` in DT component?

**Comment by Thorium** [comment]
Ok I think the issue is actually fine with SwaggerProvider because it lists `frameworks: net6.0, netstandard2.0` in paket.dependencies thus it should restrict already the loading. Sorry, trying to debug "what is loaded by VS on design-time and why" seems not to be trivial.
