### ISSUE TITLE
Allow for custom headers per-request

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#22]
### Description

Currently SwaggerProvider allows for injection of headers via Static Parameter when the type is first created.  These are set-only.
There are cases when one would like to be able to set headers on a per-request basis, for example

- when your API requires authentication via a Bearer token, which is subject to expiration
- when a particular consumer wants to specify different caching or content-type headers
- any number of other situations.

I'm mainly interested in the Authentication case, however.

### Known workarounds

It is difficult to do this right now, but it is possible that an Auth token could be derived through some external process and embedded in the assembly as a literal, which could then be used in the static parameter.
But that token is then stuck for the entire lifetime of the host process.

### Related information 

Considerations:

- headers could be shared and mutated with a static parameter, like the Host today. This feels a little gross to me, because the type provider is a shared resource where one consumer modifying the collection could cause issues for other consumers
- headers could be added as an optional parameter to the provided Operation member. This feels better because the headers then are truly per-request.
- the provided type could become an instance-based type, requiring a constructor to create an instance before use.

**Comment by sergey-tihon** [comment]
Releases in [v0.5.0](https://www.nuget.org/packages/SwaggerProvider)
Now you can modify Headers whenever you want on each provided instance
```fsharp
let [<Literal>] Schema = __SOURCE_DIRECTORY__ + "/Schemas/GitHub.json"
type GitHub = SwaggerProvider<Schema>
let github = GitHub("api.github.com", Headers = [|"User-Agent","Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405"|])
```
or event change every HttpRequest in any way
```fsharp
let github = GitHub(CustomizeHttpRequest=fun (req::Net.HttpWebRequest -> Net.HttpWebRequest)->req)
```

**Comment by baronfel** [comment]
This is great, thanks so much. I'll introduce it tomorrow and take it for a ride.
