### ISSUE TITLE
Support $ref in DefinitionProperty

### ISSUE THREAD

**Issue by saosebastiao** [fsprojects/SwaggerProvider#23]
### Description

The Swagger Provider doesn't support the $ref aspect of the spec

### Repro steps

let path = "swagger.json" (* uses $ref , example: instagram swagger api example *)
type PetStore = SwaggerProvider<path, "Content-Type=application/json">

### Related information 
May be related to the refs being part of the 2.0 spec, but I'm not sure.

**Comment by sergey-tihon** [comment]
@saosebastiao Could you please specify what do you expect mean by `$ref aspect of the spec`? Or what do you expect to see?

SwaggerProvider support `$ref`.

All schemes that has custom type definition uses `$ref` to reference to them.
Like here https://github.com/fsprojects/SwaggerProvider/blob/master/tests/SwaggerProvider.Tests/Schemas/PetStore.Swagger.json#L54 you see reference to https://github.com/fsprojects/SwaggerProvider/blob/master/tests/SwaggerProvider.Tests/Schemas/PetStore.Swagger.json#L675

SwaggerProvider generates .NET types for all `definitions` and resolve reference them.

**Comment by saosebastiao** [comment]
I'm getting the following error when trying to use the type provider for the Instagram API spec:

Error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: Reference to unknown type #/definitions/Media (FS3033) (FSharpTest)

The swagger file provided does indeed define a Media data type. 

Here is a repo that attempts to reproduce the error:
https://github.com/saosebastiao/FSharpTest

**Comment by sergey-tihon** [comment]
Thanks, nice sample.
Where did you get this schema?

I just wonder why your [Instagram API swagger.json](https://github.com/saosebastiao/FSharpTest/blob/master/FSharpTest/swagger.json) differ from [one listed in API.guru](https://apis-guru.github.io/api-models/instagram.com/1.0.0/swagger.json) // cc: @IvanGoncharov

**Comment by saosebastiao** [comment]
I got it from the sample sets available for the demo editor at
http://editor.swagger.io/#/

**Comment by IvanGoncharov** [comment]
@sergey-tihon Instagram doesn't provide official Swagger files.
Both files are manually written, swagger-editor version is intended as a sample.
So it's incomplete and out of sync.
For APIs.guru I use this version:
https://github.com/darklynx/swagger-api-collection/blob/master/api/yaml/instagram.yaml

**Comment by sergey-tihon** [comment]
Fix released in [v0.4.0](https://www.nuget.org/packages/SwaggerProvider/0.4.0)
