### ISSUE TITLE
Cannot execute Method with optional parameters

### ISSUE THREAD

**Issue by ibrahim324** [fsprojects/SwaggerProvider#236]
Whenever i try to execute a generated async method with an optional argument, it throws the following error (in my console):
Swagger.OpenApiException: One or more of the query params are invalid. The repsonse body will contain more info
I set PreferAsync=true and the generated method has the following signature: 
``Client.GetV4Sports(apiKey: string, ?all: bool) : Async<OddsApi.OperationTypes.GetV4Sports_Response_Item array>
``
Repro:
Refer to the following Schema for repro:
[Odds Api ](https://api.swaggerhub.com/apis/the-odds-api/odds-api/4/swagger.json
)

Here are the docs:
[OddsApi Docs](https://app.swaggerhub.com/apis-docs/the-odds-api/odds-api/4#/sports/get_v4_sports
)
An Api-Key is needed, but maybe someone came across this issue in other contexts. 
I assign my type provider like this:

`type OddsApi =  OpenApiClientProvider<"https://api.swaggerhub.com/apis/the-odds-api/odds-api/4/swagger.json", PreferAsync=true>`

I expect a list of Sports, either in-season or all, as per the docs.

here is how i call the api, inside a bolero service:
```
getSports = fun all -> async{
                let! sports =
                    match all with
                    | Some all ->
                        match all with
                            | true -> client.GetV4Sports(key, Some true)
                            | false -> client.GetV4Sports(key, Some false)
                    | None -> client.GetV4Sports(key, None)
...
```
### Related information

* Operating system: MacOS
* .NET Runtime, CoreCLR or Mono Version: net7.0

**Comment by ibrahim324** [comment]
@sergey-tihon Thanks for your reply, I am not familiar with these tools but will see how to get the response body with them.

**Comment by ibrahim324** [comment]
@sergey-tihon I got the error message with Fiddler, and it says

`{"message":"Invalid all parameter. Must be true or false"}`

**Comment by sergey-tihon** [comment]
Cool, please share the URL of the request or screenshot

**Comment by ibrahim324** [comment]
@sergey-tihon  Sure: 
https://api.the-odds-api.com/v4/sports?apiKey="myKey"&all=True

**Comment by sergey-tihon** [comment]
soo... your api is case-sensitive? I see `&all=True` in URL, it means that the request is serialised correctly.

**Comment by sergey-tihon** [comment]
that how `True.ToString()` works in .NET

https://github.com/fsprojects/SwaggerProvider/blob/master/src/SwaggerProvider.Runtime/RuntimeHelpers.fs#L64C30-L64C43

**Comment by sergey-tihon** [comment]
as a workaround, you may try to implement `DelegatingHandler` that modifies the request before the submission and replaces `True` by` true` in the url.

https://fsprojects.github.io/SwaggerProvider/#/Customization#request-interception

**Comment by ibrahim324** [comment]
@sergey-tihon I guess I worked something out in interactive notebooks:

```
#r "nuget: SwaggerProvider"
open SwaggerProvider
open System
open System.Net.Http


type OddsApi = 
    OpenApiClientProvider<
        "https://api.swaggerhub.com/apis/the-odds-api/odds-api/4/swagger.json",
        PreferAsync=true>
let key = "SomeKey"


type Handler(messageHandler) =
    inherit DelegatingHandler(messageHandler)
    override __.SendAsync(request, cancellationToken) = 
        let uriBuilder = UriBuilder(request.RequestUri)
        let query = System.Web.HttpUtility.ParseQueryString(uriBuilder.Query)
        query.["all"] <- query.["all"].ToLower()
        uriBuilder.Query <- query.ToString()
        request.RequestUri <- uriBuilder.Uri
        base.SendAsync(request, cancellationToken)

let baseAddress = new Uri("https://api.the-odds-api.com")
let handler1 = new HttpClientHandler (UseCookies = false)
let handler2 = new Handler(handler1)
let httpClient = new HttpClient(handler2, true, BaseAddress=baseAddress)

let client = OddsApi.Client(httpClient)


client.GetV4Sports(key, Some true) |> Async.RunSynchronously
```

This applies ToLower on a specific query parameter and returns the expected values.
Thanks for the guidance and help!
