### ISSUE TITLE
Investigate useage of Dictionary<'k, 'v>.Add('k, 'v) instead of indexer.

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#27]
### Description

I believe that there's a dictionary Add exception leaking out of the provider that could be easily worked around by changing usages of .Add(key, value) to use the indexer : [key] <- value.
Per MSDN, the indexer never throws.  

### Repro steps

run the provider pointed at the json config in [this gist](https://gist.github.com/baronfel/57d3b963e021a1ee2f08af680568c1e0)

### Expected behavior

It would be great if the duplicate key was either avoided using the indexer, or the key that caused the error was reported.

### Actual behavior

you get this error: 
![image](https://cloud.githubusercontent.com/assets/573979/14722089/73d5cbf4-07cf-11e6-8361-9b780b7dafef.png)

### Known workarounds

None at the moment, investigating to see if there's an error in my schema.

### Related information 

Swagger Provider 0.5 on f# 4.0

**Comment by sergey-tihon** [comment]
Fix released in [v0.5.1](https://www.nuget.org/packages/SwaggerProvider/0.5.1)
