### ISSUE TITLE
201 status codes should be used as a return type for operations

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#34]
### Description

POSTs that return a 201 Created can return a model, and the operation compiler should be updated to allow for that.

### Repro steps

Please provide the steps required to reproduce the problem

Using [this swagger](https://gist.github.com/baronfel/67c0cb066cc2745d082b51a3e313c28b), the ThingGetThing POST operation returns unit

### Expected behavior

The operation should return Thing.GetModel

### Actual behavior

Unit :(

### Known workarounds

Change the response code to 200

### Related information 
SwaggerProvider 0.5.1

**Comment by baronfel** [comment]
I'll see if I can send a PR in for this after doing a bit of research around response codes that return a successful model

**Comment by sergey-tihon** [comment]
Released in [0.5.2](https://www.nuget.org/packages/SwaggerProvider/0.5.2)
