### ISSUE TITLE
F# 3.0

### ISSUE THREAD

**Issue by yodiz** [fsprojects/SwaggerProvider#42]
### Description

I get the following error when using F# 3.0 compiler, in Visual studio 2012
Warning 4   Referenced assembly '<path>\packages\SwaggerProvider.0.5.3\lib\net45\SwaggerProvider.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found    

Same project works fine in VS2015 using F# 4.0

Is the minimum F# compiler version 4.0?
### Repro steps
1. Create project in VS 2015, create a SwaggerProvider<..>, Build
2. Open project in VS2012 and try to compile.
### Expected behavior

Compile and work in VS2012
### Actual behavior

Build error
### Known workarounds

No workaround
### Related information
- Windows 7
- SwaggerProvider 0.5.3
- 4.5.1

**Comment by sergey-tihon** [comment]
Yes, it is F# 4.0 now, but it is possible to support F# 3.0
If we will do it now, it force F# 4.0 user always add assembly redirect for `FSharp.Core.dll` (what is less than ideal)

Let's postpone it slightly until I understand how to rewrite types in quotation according to user's environment ;)

**Comment by sergey-tihon** [comment]
No plans to support F# 3.0 in the near future. According to [this](https://twitter.com/sergey_tihon/status/860770073983807488) I suppose it will stay F# 4.0.
