### ISSUE TITLE
NTLM authentication

### ISSUE THREAD

**Issue by vasily-kirichenko** [fsprojects/SwaggerProvider#50]
### Description

Being running on Windows, the type provider should use current windows user credentials as it's downloading swagger schema.

### Expected behavior

It works.

### Actual behavior

![image](https://cloud.githubusercontent.com/assets/873919/18130398/91ea6de0-6f97-11e6-95ef-cea0dc69ac67.png)

### Known workarounds

No.

**Comment by sergey-tihon** [comment]
The workaround is to download schema to the file on disk ;)

**Comment by vasily-kirichenko** [comment]
Fixed in https://github.com/fsprojects/SwaggerProvider/pull/51

**Comment by sergey-tihon** [comment]
Released in [v0.5.6](https://www.nuget.org/packages/SwaggerProvider/0.5.6)
