### ISSUE TITLE
Documentation usage images are out of sync with current usage

### ISSUE THREAD

**Issue by baronfel** [fsprojects/SwaggerProvider#55]
### Description

The images on the splash page for SwaggerProvider show Operations as static members of a type, ie `PetStore.Pets.AddPet()` instead of `new PetStore().AddPet(PetStore.Pet()))`

### Repro steps

Install the provider
Point it to the default petstore schema http://petstore.swagger.io/v2/swagger.json
Try to do what's shown in the images on the docs page

### Expected behavior

The docs images match up with current behavior

### Actual behavior

They don't :(

### Known workarounds

Instantiate the provider and then things work, though again out of sync with the docs

**Comment by baronfel** [comment]
I'm willing to submit new images to get this up to date, perhaps over the weekend.

**Comment by sergey-tihon** [comment]
@baronfel Thx, I will update docs soon

**Comment by sergey-tihon** [comment]
Done here - http://fsprojects.github.io/SwaggerProvider/

**Comment by baronfel** [comment]
Holy smokes, Sergey the new site is gorgeous! Thanks for updating that :)
