### ISSUE TITLE
Support `security` & `securityDefinitions `

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/SwaggerProvider#67]
Find out simpler way to support security in schema (constructor params?)
https://api.apis.guru/v2/specs/amadeus.com/1.2/swagger.json

**Comment by 7sharp9** [comment]
Is oauth2.0 supported?

**Comment by sergey-tihon** [comment]
No by TP itself, so we do nothing with information from `security` section
but we allow customizing all web request http://fsprojects.github.io/SwaggerProvider//petstore.html#Generated-constructor and https://stackoverflow.com/questions/37566751/what-should-i-do-to-prevent-a-401-unauthorised-when-using-the-swagger-type-provi/37628857#37628857 so technically you could add any authentication method.

**Comment by sergey-tihon** [comment]
For now auth should be added as default HttpClient header or as HttpClient middleware
http://fsprojects.github.io/SwaggerProvider/#/Customization#authentication
