### ISSUE TITLE
SwaggerProvider reported an exception object not set to a reference

### ISSUE THREAD

**Issue by willsam100** [fsprojects/SwaggerProvider#75]
### Description
Using Mono.5.0.0.78 the following error occurs:
"swaggerProvider reported an exception object not set to a reference"

### Repro steps
- Install mono.5
- create project with latest version of SwaggerProvider from nuget
- load the petStore example
- see the exception (either from building on in REPL)

### Expected behaviour
Not to throw an exception

### Actual behaviour
throws exception: 'object not set to a reference'

### Known workarounds
Roll back to Mono.4.8

### Related information 
- Mac 10.11.6
- Tried with Xamarin Studio, Visual Studio for Mac and VS Code Ionide, and REPL. The error occurs on all
- Visual Studio for Mac is in preview and so only supports alpha releases ie Mono.5

Might be caused by the following:
https://github.com/fsharp/fsharp/issues/702#issuecomment-295860706

**Comment by jimbobbennett** [comment]
Tested with Mono Framework 5.0.0.94 and I can still reproduce the error

**Comment by sergey-tihon** [comment]
Ok, thanks, seems that I can reproduce it in this PR https://github.com/fsprojects/SwaggerProvider/pull/76

With different Mono versions:
- [beta](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629593) = `(Stable 5.0.0.94/1d0445b Wed May  3 17:40:24 UTC 2017)`
- [nightly](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629594) = `(Nightly 5.3.0.262/137e1e7 Tue May  2 14:47:25 UTC 2017)`

I see a lot of messages from the compiler 

> non-IL or abstract method with non-zero RVA

[there are couple](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629593#L1905-L1908) directly before an error from TP compilation. So it may be related.

There are no such warnings with `(Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017)` - [see here](https://travis-ci.org/fsprojects/SwaggerProvider/jobs/230629592)

// cc: @nosami

**Comment by dsyme** [comment]
Please update to use the latest version of ProvidedTypes.fs, as described in  https://github.com/fsprojects/FSharp.TypeProviders.StarterPack/issues/121

**Comment by sergey-tihon** [comment]
Fix released in [Swagger Provider 0.7.0](https://www.nuget.org/packages/SwaggerProvider/) and should work correctly on Mono v5.0.1.1 and later
