### ISSUE TITLE
Error FS3033: The type provider could not load file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by landocalris** [fsprojects/SwaggerProvider#77]
### Description

Adding SwaggerProvider to a Console application causes the build to fail.

### Repro steps

1. Create a Visual F# Console Application

2. Add SwaggerProvider using NuGet

3. Make the Program.fs file look like this:
```fsharp
open SwaggerProvider

[<Literal>]
let schema = "http://petstore.swagger.io/v2/swagger.json"
type PetStore = SwaggerProvider<schema>

[<EntryPoint>]
let main argv =
   printfn "Hello World"
   0
```

4. Build the project

5. Output from Build shows this error:
> error FS3033: The type provider 'SwaggerProvider.SwaggerTypeProvider' reported an error: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)

### Known workarounds

It works in F# interactive.

### Related information 

* Operating system
> Windows 10 Pro
>Version	10.0.15063 Build 15063
>System Type	x64-based PC

* packages.config
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FSharp.Core" version="4.1.17" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="net461" />
  <package id="SwaggerProvider" version="0.7.0" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.3.1" targetFramework="net461" />
</packages>
```
* .NET Runtime
> 4.6.1
* F# runtime
> 4.4.1.0
* Visual Studio Info
> Microsoft Visual Studio Enterprise 2017 
Version 15.2 (26430.12) Release
VisualStudio.15.Release/15.2.0+26430.12
Microsoft .NET Framework
Version 4.7.02046

>Installed Version: Enterprise

>Visual F# 4.1   00369-90250-00627-AA934
Microsoft Visual F# 4.1

**Comment by sergey-tihon** [comment]
@landocalris Thank you for so detailed issue description!
I think that easiest solution (at least for now) is to bump dependency version to 10.0.2
Please try [Swagger Provider v0.7.1](https://www.nuget.org/packages/SwaggerProvider/0.7.1) and reopen this issue if something.

**Comment by landocalris** [comment]
Thank you for your fast response.  That fixed it.  Thank you!
