### ISSUE TITLE
Client-side caching ?

### ISSUE THREAD

**Issue by flotrek** [fsprojects/SwaggerProvider#79]
Hello,
I'm looking to implement a caching middleware (based on local and/or distributed memory) to use with this awesome swaggerProvider.
Is that something wise to implement within the TypeProvider itself ?

**Comment by sergey-tihon** [comment]
It is impossible right now, but the idea generally makes sense ... 
But technically we could pass each HTTP call thought some pluggable caching component (without caching by default)

**Comment by sergey-tihon** [comment]
It is already possible with latest released beta using HttpClient middleware / custom DelegatingHandler - http://fsprojects.github.io/SwaggerProvider/#/Customization#request-interception
