### ISSUE TITLE
Provider not updating after schema changes or new schema url

### ISSUE THREAD

**Issue by sjuberman** [fsprojects/SwaggerProvider#84]
### Description

Provider does not update when updating schema or when changing schema URL

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a Console application in VS2017
2. Add SwaggerProvider reference
3. Add a new type (The PetStore example for example.)
4. Change the schema URL to another valid Swagger schema
5. Notice that the provided types do not change

GIF that shows the problem:
![typeproviders2](https://user-images.githubusercontent.com/5622403/29518153-cb51afde-8667-11e7-9c64-be85d43592ba.gif)

### Expected behavior

The provided types should update

### Actual behavior

The provided types do not update

### Known workarounds

Create new type every time you change the URL or schema

### Related information 

* OS: Windows10
* SwaggerProvider version: 0.8
* Visual Studio 2017 Update 3.1

**Comment by sergey-tihon** [comment]
Hmm... interesting... Do you experience the same behavior when do not use `[<Literal>]` variable and do paste schema URL directly into type definition `SwaggerProvider<"url_here">`?

On TP side we do caching using schemaUrl... and it should work correctly if IDE does can to TP after each schemaUrl change...

**Comment by sergey-tihon** [comment]
Please do try [v0.8.1](https://www.nuget.org/packages/SwaggerProvider/0.8.1)

**Comment by sjuberman** [comment]
@sergey-tihon This works perfectly now. Thank you very much. Even updates when I change the remote schema. How is it getting the updates? Is it polling the URL?

**Comment by sjuberman** [comment]
Alrighty, this makes the user experience a whole lot better. I'll close this issue. Thanks for the quick response!
