### ISSUE TITLE
Support for netstandard2.0

### ISSUE THREAD

**Issue by 7sharp9** [fsprojects/SwaggerProvider#86]
### Description

Support in netstandard2.0 that I can use Swagger in a core net standard project referenced by mobile applications

I wonder if there is an elaborate work around netstandard2.0 or interim patch while things are finally worked out?

**Comment by sergey-tihon** [comment]
Not yet =(
We have some discussion here  - https://github.com/fsprojects/SwaggerProvider/issues/54
but the main stoppage is that it is generative type provider.

It may be possible if we decide to convert it to erased TP (or support both options) and try this workaround https://github.com/Microsoft/visualfsharp/issues/3303 ...

But as I know there is no TP (even erased) completely migrated to `netstandard2.0`

**Comment by 7sharp9** [comment]
I wonder if you could create a pure facade for net standard that called into one where your usage is in a 4.6.1 project, like an elaborate bait and switch.

**Comment by sergey-tihon** [comment]
@7sharp9  TBH, I do not understand what are you talking about ... at least yet.

**Comment by 7sharp9** [comment]
:-)  Why do you need to target a generative?  So C# can consume it?

**Comment by sergey-tihon** [comment]
Yes, this was the goal. primarily for those who do UI in C#

**Comment by enricosada** [comment]
just curiosity.
Is hard to do this also as erasing one in addition to generative? the two TP types are a lot different?

**Comment by sergey-tihon** [comment]
It is possible to have both, but we are working on migration to new TP SDK that should allow as to compile netstandard2.0/netcore2.0 at some point.

**Comment by dsyme** [comment]
@sergey-tihon I wrote up notes of what it means to move an existing type provider to support both .NET Standard and loading into .NET Core0-based F# tooling https://github.com/fsprojects/FSharp.TypeProviders.SDK#updating-a-type-provider-to-be-suitable-for-use-with-the-net-sdk

I'd love to get this TP shifted along these lines.  Who is up for working on this?

**Comment by panesofglass** [comment]
I am interested in helping, though time is hard to come by. Has anyone started this process?

**Comment by ctaggart** [comment]
I think the next step for this project is finishing up the PR for the new project format migration https://github.com/fsprojects/SwaggerProvider/pull/110

**Comment by panesofglass** [comment]
If you need something immediately, you may find https://github.com/Dzoukr/OpenAPITypeProvider useful.

**Comment by sergey-tihon** [comment]
It should be already done in  [v0.10.0-beta05](https://www.nuget.org/packages/SwaggerProvider/0.10.0-beta05)

**Comment by reaysawa** [comment]
@sergey-tihon Is the source for this beta version available somewhere?

**Comment by sergey-tihon** [comment]
@reaysawa Yes, `dev` branch of this repo - https://github.com/fsprojects/SwaggerProvider/tree/dev
