### ISSUE TITLE
Using the SwaggerProvider in a library

### ISSUE THREAD

**Issue by kMutagene** [fsprojects/SwaggerProvider#87]
Is it possible to use the SwaggerProvider in a library using an embedded ressource, similar to the F# Data [JSONProvider](http://fsharp.github.io/FSharp.Data/library/JsonProvider.html) ?

**Comment by sergey-tihon** [comment]
Hmm.. Interesting question! SwaggerProvider does not support embedded resources, but I am not sure that we have to...

SwaggerProvider is generative type provider, so during the library compile time all types should be compiled and merged into target assembly.

**Comment by kMutagene** [comment]
hi sergey,
thank you for your answer!
> [...]during the library compile time all types should be compiled and merged into target assembly

In our case the problem was that building worked, but after referencing the dll the generated methods/types were not found. After fixing the file path, everything worked as you said.
