### ISSUE TITLE
Extract swagger parsing code into separate library?

### ISSUE THREAD

**Issue by danyx23** [fsprojects/SwaggerProvider#90]
### Description

The SwaggerProvider project includes the code to parse what looks like a significant subset of swagger v2. I think it would be valuable to extract this into it's own F# library. It might also make upgrading to openapi v3 cleaner.

Please let me know if you would be interested in a PR towards this end (can't promise I will get around to doing it soon though). Thanks!

**Comment by sergey-tihon** [comment]
What is your use case? What you plan to do with parsed schema?

I do not see any reason (for now) to create the separate NuGet package for the parser, we can move the code to `SwaggerProvider.Runtime.dll` and make public and easy to use. This also means slightly different runtime dependencies, we have to add the dependency to YAML parsing library to support specs in YAML format, but it definitely doable.

**Comment by sergey-tihon** [comment]
SwaggerParser in released in [v0.10.0-alpha1](https://www.nuget.org/packages/SwaggerProvider/0.10.0-alpha1)

It should work like 
```fsharp
open Swagger.Parser

let schema = SwaggerParser.parseSchema str
```

<img width="891" alt="2017-11-23_0916" src="https://user-images.githubusercontent.com/1197905/33160631-00c045fc-d02f-11e7-9cf7-48a30d170791.png">

**Comment by danyx23** [comment]
Cool, thanks! I might need a more complete part of the swagger information (e.g. custom extensions starting with x-) - I'll explore more and get back in touch once I know more.

**Comment by sergey-tihon** [comment]
I do plan to remove custom parser from the codebase and migrate to [Microsoft.OpenApi.Readers](https://www.nuget.org/packages/Microsoft.OpenApi.Readers/) that will support `v2` and `v3` schemas ( when known bugs will be fixed)

Please, do not rely on the parser exposed in `v0.10.0-alpha1`. I will track future progress here https://github.com/fsprojects/SwaggerProvider/issues/98
