### ISSUE TITLE
Full init constructor for provided types

### ISSUE THREAD

**Issue by yodiz** [fsprojects/SwaggerProvider#91]
### Description
As it is now Swaggerprovider generates mutable classes for objects. Would it be possible to generate immutable F# records? 

Options types for non required fields would also be nice :)

If F# Records are not possible, is it possible to have a default constructor on the generated type that sets all properties of the object? This would minimize risk of not setting an property by accident. And also if the underlying swagger-specification change, and a property is added on the object: You would get a compile-error that you need to set the property.

**Comment by sergey-tihon** [comment]
> As it is now Swaggerprovider generates mutable classes for objects. Would it be possible to generate immutable F# records?

According to my knowledge - no, TP SDK does not allow to emit record types https://github.com/fsharp/fslang-suggestions/issues/154 - you may vote for this feature if you like to see it in some future.

> Options types for non required fields would also be nice :)

SwaggerProvider already provides `Option<T>` when T is not nullable - see [here](https://github.com/fsprojects/SwaggerProvider/blob/master/src/SwaggerProvider.DesignTime/DefinitionCompiler.fs#L54-L74) But when the T is nullable it is an ambiguous question what to provide. IMHO it is not good idea to generate object model that allow to have `Some(null)` values.

> If F# Records are not possible, is it possible to have a default constructor on the generated type that sets all properties of the object? This would minimize risk of not setting an property by accident. And also if the underlying swagger-specification change, and a property is added on the object: You would get a compile-error that you need to set the property.

I understand you intend, but we still need default parameter-less constructor and property setters to allow serializer (`JSON.NET`) to deserialize server response to provided model classes. So we probably cannot avoid the risk of accident property setting.

The only thing we can do is to add one more constructor with enormous number of parameters that initialize all properties.

**Comment by yodiz** [comment]
Having one empty constructor, and another one that set all the properties of the object would be very helpfull. Any idea when and if you will get around to it? I could give it a try, but i dont have much experience on the coding-side of typeproviders.

I would prefer having fields marked with required=false generated as an Option<_>. I see your point, but now you get no distinction if fields are required or not. How about a setting for SwaggerProvider<NonRequiredFieldsAsOptions=true> , or something of the sort :)

**Comment by sergey-tihon** [comment]
No ETA for release (I do plan big changes in provider) but initial implementation is here https://github.com/fsprojects/SwaggerProvider/pull/92/commits/8eb0d889498bd240affcfc8559ae8e81df740717

![2017-11-22_0853](https://user-images.githubusercontent.com/1197905/33112326-bbca9536-cf63-11e7-83c5-08ba8277e34b.png)

**Comment by sergey-tihon** [comment]
if the property type is a number then you will see difference in types ...

`type=number` + `required=true` -> `int`
`type=number` + `required=false` -> `Option<int>`

but when the property is `string` then it will `string` for all both options because `null` is the correct value for the string. 

What will be the benefit of generation `Option<string>` properties?

**Comment by yodiz** [comment]
Oh great, i'll test it. Thanks and well done :)

About the Option<_>:
I just prefer that the fields optionality is described in a "typed manner". 

Let's assume you have an Object Pet that has a Required PrimaryCategory of the type PetCategory and another field SecondaryCategory that is optional. With an option type for reference-objects aswell that are optional i just think it gets more intuitive.

No option type: 
{
  PetId : int
  PrimaryCatergory : PetCategory
  SecondayCategory : PetCategory // <-- is it required or not?
}

With option type:
{
  PetId : int
  PrimaryCatergory : PetCategory
  SecondayCategory : PetCategory option // <-- Optionality explained through type-system
}

I agree that its kind of dumb that you can provide Some(null). And it's just a matter of preference. For my usage i prefer the option type, but i get that you might not want that.

Thanks for the constructor-thingy again, And for all the type providers :)

**Comment by baronfel** [comment]
@sergey-tihon perhaps for the case when the user has requested option types, we can do an Option.ofObj on the deserialized response, to eliminate Some(null) cases and keep the model as pure as possible?

**Comment by sergey-tihon** [comment]
@baronfel yes, probably we should try it. I did open new issue to track this request #93 

I close this one because full-init ctor is released in `v0.10.0-alpha1` package.
