### ISSUE TITLE
Migrate to Microsoft.OpenApi.Readers

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/SwaggerProvider#98]
Seems like we can reuse MS in scope of https://github.com/Microsoft/OpenAPI.NET
provide readers (parsers) for OpenAPI v3 and OpenAPI v2(aka Swagger) schemas
https://www.nuget.org/packages/Microsoft.OpenApi.Readers/

Maybe we could reuse them...

https://swagger.io/blog/announcing-openapi-3-0/

**Comment by panesofglass** [comment]
Is this still todo?

**Comment by sergey-tihon** [comment]
@panesofglass Yes, sure, but `OpenApi.NET` is not ready yet - the latest version on NuGet still fails on 77 `apis.guru` schemas - https://github.com/Microsoft/OpenAPI.NET/pull/190#issuecomment-365836110

**Comment by sergey-tihon** [comment]
![win10_-_fall_creators_and_app_store](https://user-images.githubusercontent.com/1197905/38698863-22aa3c84-3e9f-11e8-96b1-2e8ae4227156.png)
Only 15 schemas still fails with NullRefs during schema parsing with `1.0.0-beta016` so `Microsoft.OpenApi` is close to release

**Comment by ctaggart** [comment]
How about now? There have been 5 releases since then, including a stable release with bug fix:
https://www.nuget.org/packages/Microsoft.OpenApi.Readers

![image](https://user-images.githubusercontent.com/80104/41316839-0eaf69c2-6e59-11e8-8e24-5c725d483dc1.png)

**Comment by sergey-tihon** [comment]
I hope so, but I haven't tried new version yet.
I'll try again when my provided methods work on .net core

**Comment by leofischer** [comment]
Thats okay, I am actually asking so that I can deserialize with https://github.com/fsprojects/OpenAPITypeProvider (which is only openapi3).  Is there any way to access the deserializer directly (e.g. for an API which is receives these requests) so that the same type definition can be reused?  If not, would you have any suggestions on what might work @sergey-tihon?

**Comment by bigjonroberts** [comment]
ping

**Comment by sergey-tihon** [comment]
Implemented in #117
